### ISSUE TITLE
[BUG] Bot doesn't respond.

### ISSUE THREAD

**Issue by swatky** [Adiixyz/selfbotz#4]
Hello, I can't use it, I send the command with the right prefix, but the bot doesn't respond.![image](https://user-images.githubusercontent.com/40281950/130241223-c7f8b34b-cca6-4085-8f41-7bf285fba82f.png)The console informs you that you have received the message, but nothing happens in the chat.

**Comment by Adiixyz** [comment]
wait... i will fix it...

**Comment by swatky** [comment]
> wait... i will fix it...
ok

**Comment by Adiixyz** [comment]
done fix

**Comment by swatky** [comment]
> done fix

I downloaded the source again, but the error still persists, now it says "command" on the console, but it still doesn't respond. :/
![image](https://user-images.githubusercontent.com/40281950/130244610-7df4a58e-a7db-4954-9996-2593a3209cd0.png)
![image](https://user-images.githubusercontent.com/40281950/130244839-06eff12d-b064-4be0-bd05-c7c79f5d447c.png)

**Comment by Adiixyz** [comment]
please use termux
maybe it work

**Comment by swatky** [comment]
> please use termux
> maybe it work

Alright, I'll try later, I'm out of cell phone to use termux now, thank you very much for your help.
